name: release

on:
 push:
  tags:
    - v[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy-forge:
    name: Deploy to Forge
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          clean: true
      - name: "PDK Build"
        uses: docker://puppet/pdk:nightly
        with:
          args: 'build'
      - name: "Push to Forge"
        uses: docker://puppet/pdk:nightly
        with:
          args: 'release publish --forge-token ${{ secrets.FORGE_API_KEY }} --force'
